[icedos.desktop.cosmic.windowManagement]
cli = false

[icedos.desktop.cosmic.windowManagement.focus]
cursorFollowsFocus = false

[icedos.desktop.cosmic.windowManagement.snapWindowsToEdges]
enable = true
threshold = 25
