[icedos.desktop.cosmic.window-management]
cli = false

[icedos.desktop.cosmic.window-management.focus]
cursorFollowsFocus = false

[icedos.desktop.cosmic.window-management.snap-windows-to-edges]
enable = true
threshold = 25
