[icedos.desktop.cosmic.patches.cosmic-applets]
steamGameIconMatcher = false

[icedos.desktop.cosmic.patches.cosmic-comp]
dmemForegroundBooster = false
fixTilingHintClipping = false
perWindowKeyboardLayout = false

[icedos.desktop.cosmic.patches.cosmic-notifications]
windowMatchingRoundness = false

[icedos.desktop.cosmic.patches.cosmic-osd]
keyboardLayoutOsd = false

[icedos.desktop.cosmic.patches.cosmic-panel.autohide]
alwaysHide = false

[icedos.desktop.cosmic.patches.xdg-desktop-portal-cosmic]
useGtkFilePicker = false
