[icedos.desktop.cosmic.patches.cosmic-comp]
disableMonitorsOnLock = false
fixTilingHintClipping = false
fixWakeFromSleep = false
perWindowKeyboardLayout = false

[icedos.desktop.cosmic.patches.cosmic-osd]
keyboardLayoutOsd = false

[icedos.desktop.cosmic.patches.cosmic-panel.autohide]
alwaysHide = false
